### ISSUE TITLE
Libkolab does not load on Roundcube 1.6.5

### ISSUE THREAD

**Issue by fabio-florencio** [kolab-roundcube-plugins-mirror/libkolab#10]
It seems the is a problema with libkolab and Roundcube 1.6.5

I have Roundcube insalled on a Pleks Obsidian Server, and since last upgrade deployed today in my server I have problems when saving tasks, provided by Kolab.

I can see this error in log:

PHP Error: Failed to load plugin file /usr/share/psa-roundcube/plugins/libkolab/libkolab.php in /usr/share/psa-roundcube/program/lib/Roundcube/
rcube_plugin_api.php on line 193 (POST /?_task=mail&_action=refresh)

PHP Error: required kolabformat module not found (GET /?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=890&_mbox=INBOX.Arquivados&_framed=1&_action=preview)

The result is that when I'm trying to save a task, an error returns:

![Captura de tela de 2023-11-09 16-06-37](https://github.com/kolab-roundcube-plugins-mirror/libkolab/assets/98746225/4c545810-ad5a-4928-a837-ddb26499b1f8)

Could please verify?

**Comment by alecpl** [comment]
This repository is just a mirror. You should talk to Plesk Support or Kolab Support. Looks like a problem with the system not plugins itself.
