### ISSUE TITLE
PHP Fatal error:  Call to undefined method rcmail::upload_form()

### ISSUE THREAD

**Issue by twisterbr** [kolab-roundcube-plugins-mirror/libkolab#2]
Roundcube 1.1.1
Using the latest calendar plugin
Just installed. Getting the error:

logs/errors:[27-Jan-2020 11:40:07 America/Sao_Paulo] PHP Fatal error:  Call to undefined method rcmail::upload_form() in /var/www/--/plugins/libkolab/lib/kolab_attachments_handler.php on line 74

Any clue?

**Comment by alecpl** [comment]
Too old Roundcube version. Other Kolab plugins like Calendar specify minimal version, I guess we should do the same for this plugin.
