### ISSUE TITLE
RuntimeError plugins/libkolab/skins/images/corner-handle.svg missing

### ISSUE THREAD

**Issue by mikecastrodemaria** [kolab-roundcube-plugins-mirror/libkolab#3]
lessc -x plugins/libkolab/skins/elastic/libkolab.less > plugins/libkolab/skins/elastic/libkolab.min.css

RuntimeError: error evaluating function `data-uri`: ENOENT: no such file or directory, open '.../plugins/libkolab/skins/images/corner-handle.svg' in .../skins/elastic/styles/variables.less on line 55, column 25:
54 // Additional icons
55 @icon-resize-corner:    data-uri("image/svg+xml;charset=utf-8", "../images/corner-handle.svg"); // size: 16x16
56 @icon-file-drop:        data-uri("image/svg+xml;charset=utf-8", "../images/download.svg");

**Comment by alecpl** [comment]
The way to build the skin is described in https://git.kolab.org/diffusion/RPK/browse/master/less-build.sh. This is just a mirror, we do not accept changes to the original code.
