### ISSUE TITLE
Sharing calendar

### ISSUE THREAD

**Issue by elg0ch0** [kolab-roundcube-plugins-mirror/libkolab#8]
Hi

Is the "share" calendar option working for anyone?

I'm trying it out but I can only edit Name, Color, and Show Reminders

![image](https://user-images.githubusercontent.com/31018739/212753265-a4b5099a-cf99-4395-aca1-0d70802b5903.png)

**Comment by alecpl** [comment]
Only the Kolab driver supports sharing. In the next version the title will be "Edit calendar".
